### ISSUE TITLE
Pokemon images used and drop down

### ISSUE THREAD

**Issue by Darshan1412** [FallenDeity/PokeDex-Website#2]
Hi actually i was working on the pokedex so i wanted to ask about the from where you are using the pokemon images in search tab and how do you add all new gen pokemon and how you added the drop down to work with api

**Comment by FallenDeity** [comment]
images are from pokeapi then official artwork value from the sprite resources. dropdown select made using shadcn. and using a pokenode-ts library which has cache support to request Pokemon gen wise based on drop-down selected option

**Comment by Darshan1412** [comment]
hi can you help me for this changes in my project i am working on if you can then send me your email id

**Comment by FallenDeity** [comment]
help in what sense? fork and write the code? you can just take parts of the code u need from my repo
